// ─── Cravio Partner Design Tokens ────────────────────────────────────────────
// Brand palette: Primary #FF6B00, Secondary #16A34A (same as customer app)

const colors = {
  light: {
    text: '#111827',
    tint: '#FF6B00',
    background: '#F8F9FB',
    foreground: '#111827',
    card: '#FFFFFF',
    cardForeground: '#111827',
    surface: '#FFFFFF',
    surfaceVariant: '#F3F4F6',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#16A34A',
    secondaryForeground: '#FFFFFF',
    muted: '#F3F4F6',
    mutedForeground: '#6B7280',
    accent: '#FFF7ED',
    accentForeground: '#FF6B00',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#22C55E',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    error: '#EF4444',
    errorForeground: '#FFFFFF',
    border: '#E5E7EB',
    input: '#E5E7EB',
    textSecondary: '#6B7280',
  },
  dark: {
    text: '#F9FAFB',
    tint: '#FF6B00',
    background: '#111827',
    foreground: '#F9FAFB',
    card: '#1F2937',
    cardForeground: '#F9FAFB',
    surface: '#1F2937',
    surfaceVariant: '#374151',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#16A34A',
    secondaryForeground: '#FFFFFF',
    muted: '#374151',
    mutedForeground: '#9CA3AF',
    accent: '#1C1917',
    accentForeground: '#FF8C38',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#22C55E',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    error: '#EF4444',
    errorForeground: '#FFFFFF',
    border: '#374151',
    input: '#374151',
    textSecondary: '#9CA3AF',
  },
  radius: 12,
};

export default colors;
